add_newline = false
# A minimal left prompt
format = """$shell$directory$character"""
palette = "catppuccin_mocha"
# move the rest of the prompt to the right
right_format = """$all"""
command_timeout = 1000

[directory]
home_symbol = " "

[directory.substitutions]
"Documents" = "󱔗 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
format = '[$symbol$branch(:$remote_branch)]($style)'

[aws]
format = '[$symbol(profile: "$profile" )(\(region: $region\) )]($style)'
disabled = false
style = 'bold blue'
symbol = " "

[golang]
format = '[ ](bold cyan)'

[kubernetes]
symbol = '☸ '
disabled = false
detect_files = ['Dockerfile']
format = '[$symbol$context( \($namespace\))]($style) '
contexts = [
    { context_pattern = "arn:aws:eks:us-west-2:577926974532:cluster/zd-pvc-omer", style = "green", context_alias = "omerxx", symbol = " " },
]

[docker_context]
disabled = true

[shell]
bash_indicator = " "
zsh_indicator = '󰵁 '
fish_indicator = ' '
powershell_indicator = ' '
nu_indicator = " "
unknown_indicator = 'mystery shell'
format = '[$indicator/]($style)'
style = 'fg:teal'
disabled = false

[conda]
ignore_base = false
symbol = " "
format = '[[ $symbol$environment ](italic fg:green)]($style)'

[time]
disabled = false
time_format = "%R"                           # Hour:Minute Format
format = '[[ $time](bold fg:teal)]($style)'

[cmd_duration]
min_time = 2000
show_milliseconds = false
format = '[󰑮 $duration ]($style)'
style = "fg:green"
disabled = false
show_notifications = true
min_time_to_notify = 18000000
notification_timeout = 5000

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
